#!/bin/bash

echo "********** WELCOME TO NAGIOS INSTALLATION**********"
############################################################################################
#setenforce=0
#systemctl status firewalld
#systemctl stop firewalld
#systemctl disable firewalld
#systemctl status firewalld

############################################################################################
echo "Do you want to change hostname ?"
echo "YES. 1"
echo "NO. 2"

read -p "Enter your choice:" choice

if ((choice == 1))
then
	read -p "Enter Hostname: " hostname
	hostnamectl set-hostname $hostname
	changed=`hostname`
	ip_o=`hostname -I | awk '{print $1}'`
	echo $ip_o $changed >> /etc/hosts

elif ((choice == 2))
then
	host=`hostname`
	ip=`hostname -I | awk '{print $1}'`
	echo $ip $host >> /etc/hosts

fi

############################################################################################
echo "Add nodes to Hosts file"

read -p "How many nodes you want to add: " nodes
counter=1

while ((counter <= $nodes)); do
    read -rp "Add node entry to Hosts file (in the format IP hostname): " node_entry

    if [[ -z "$node_entry" ]]; then
        break
    fi

    echo "$node_entry" | sudo tee -a /etc/hosts

    ((counter++))
done

echo "Node entry addition complete."


############################################################################################
yum install epel-release -y
yum install http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm -y
yum install httpd -y
#To install utilities

yum -y install yum-utils -y

#To install repos

wget -P /etc/yum.repos.d https://xcat.org/files/xcat/repos/yum/latest/xcat-core/xcat-core.repo -y

#To install Nagios with Openhpc

yum install ohpc-nagios -y

#Now to start the nagios service

systemctl start nagios

#To enable the nagios

systemctl enable nagios

#To see the status

systemctl status nagios

#To start http

systemctl start httpd

#To see the status of http

systemctl status httpd

echo "Set the password to login Nagios"
read -p "Enter username: " user
read -p "Enter password: " password

htpasswd -bc /etc/nagios/passwd $user $password

#Now go to the conf.d

cd /etc/nagios/conf.d

#To overwrite the host file

sed -i '30,$d' hosts.cfg
sed -i 's/members\ HOSTNAME1\,HOSTNAME2\,HOSTNAME3\,HOSTNAME4/members\ client/g' hosts.cfg
sed -i 's/host_name\ HOSTNAME1/host_name\ client/g' hosts.cfg
ipp=`cat /etc/hosts | grep client | awk '{ print $1 }'`
sed -i 's/address\ HOST1_IP/address\ '"$ipp"'/g' hosts.cfg



#to edit the ownership for hosts.cfg and services.cfg

chown -R nagios. /etc/nagios/conf.d/hosts.cfg

#to copy the services file

cp services.cfg.example services.cfg

chown -R nagios. /etc/nagios/conf.d/services.cfg

#restart the nagios services

systemctl restart nagios

#firewall-cmd --add-service=nagios --permanent
#firewall-cmd --reload
